name: ESPHome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.project }} (esphome-${{ matrix.esphome_version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        esphome_version:
          - latest
          - stable
          - dev
        project: [ESP32-S3-4848S040]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Firmware
        uses: esphome/build-action@v7.0.0
        id: esphome-build
        with:
          yaml-file: ${{ matrix.project }}/main.yaml
          version: ${{ matrix.esphome_version }}
          complete-manifest: true
